<?php

use Illuminate\Foundation\Testing\WithoutMiddleware;
use Illuminate\Foundation\Testing\DatabaseMigrations;
use Illuminate\Foundation\Testing\DatabaseTransactions;

class AuthUserLogicTest extends TestCase
{
    public function setUp(){
        parent::setUp(); // TODO: Change the autogenerated stub
        $user = \App\User::first();
        $this->be($user);
        $this->user = $user;
    }

    /**
     * Create article
     */
    public function testWriteArticle(){

    }
    /**
     * Write comment
     */
    public function testWriteComment(){

    }
}
