<?php

use Illuminate\Foundation\Testing\WithoutMiddleware;
use Illuminate\Foundation\Testing\DatabaseMigrations;
use Illuminate\Foundation\Testing\DatabaseTransactions;

class AuthUserViewsTest extends TestCase
{
    private $user;
    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $user = \App\User::first();
        $this->be($user);
        $this->user = $user;
    }

    public function testProfileView(){
        $this->visit('/profile/'.$this->user->id)->seePageIs('/profile/'.$this->user->id);
    }

    /**
     * Test redirect for authorization user
     */
    public function testHomeRedirect(){
        $this->visit('/')->seePageIs('/home');
    }

    /**
     * User can view all articles
     */
    public function testHomeContains(){
        $res = $this->call('GET', '/home');

        $this->assertResponseOk();
        $this->assertViewHas('articles');

        $lastProductOnView = $res->original['articles'];
        $this->assertEquals(\App\Article::count(), count($lastProductOnView));
    }
    public function testLogOut(){
        $this->visit('/logout')->seePageIs('/');
    }
    public function testInvite(){
        $this->visit('/login')->seePageIs('/home');
    }
}
